
- stage: 'DeployDev'
  displayName: 'Deploy to Dev'
  # condition: and(succeeded(), eq(variables.isMain, 'true'))
  variables: 
    appName: 'bermtecdev2'
  jobs:
  - deployment: 'Dev'
     
    environment: 'Dev'
    strategy: 
       runOnce:     
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Pay-As-You-Go(63b33cff-5a1f-40bc-8e84-ad332cd71188)'
              appType: 'webAppLinux'
              WebAppName: $(appName)
              packageForLinux: '$(Pipeline.Workspace)/$(artifaceName)/$(buildConfiguration)/*.zip'
  